### ISSUE TITLE
robots.txt triggers the login process

### ISSUE THREAD

**Issue by mahdishahbazi** [GeekInTheNorth/Stott.Optimizely.RobotsHandler#35]
the AllowAnonymous is missed from  robots.txt

 ```
public RobotsController(
        IRobotsContentService service,
        IRobotsEditViewModelBuilder viewModelBuilder,
        IRobotsListViewModelBuilder listingViewModelBuilder)
    {
        _service = service;
        _editViewModelBuilder = viewModelBuilder;
        _listingViewModelBuilder = listingViewModelBuilder;
    }

    [HttpGet]
    [Route("robots.txt")]
    **[AllowAnonymous]**
    public IActionResult Index()
```

**Comment by GeekInTheNorth** [comment]
Thank you for the bug report, I'll get a fix sorted for you.

**Comment by GeekInTheNorth** [comment]
@mahdishahbazi I have now uploaded a new version to both nuget.org and nuget.optimizely.com as v2.2.0

Thank you for raising this issue to my attention.

**Comment by mahdishahbazi** [comment]
Thanks @GeekInTheNorth , you are awesome

**Comment by ellinge** [comment]
Fyi, the nuget package on Optimizely's feed is still 2.1.0
https://nuget.optimizely.com/package/?id=Stott.Optimizely.RobotsHandler
