### ISSUE TITLE
Multiple urls for sites are not resolved to same robots-configuration

### ISSUE THREAD

**Issue by ellinge** [GeekInTheNorth/Stott.Optimizely.RobotsHandler#41]
We have multi site with multiple hostnames setup for a dxp-solution.
The settings applied in the admin page for a sitedefinition (primary url defined) does not get applied to an alternate url.

https://dev.ourrootdomain.se/robots.txt https://cx.d.ourrootdomain.se/robots.txt gets different content even if both are available for the sites host-mapping (dev.ourrootdomain.se primary, cx.d.ourrootdomain.se).

Suggest one uses SiteDefinition.Current.Id instead.

**Comment by GeekInTheNorth** [comment]
Hello @ellinge,

Thank you for the contribution, I will review and potentially merge in the changes soon (along with a thank you in the readme.md :) )

I will review and potentially build a new version (for both nuget feeds) within the next 48 hours.

**Comment by GeekInTheNorth** [comment]
Closing this as the latest version is now on nuget.org and nuget.optimizely.com
