### ISSUE TITLE
Plugin Incompatibility with Optimizely CMS versions after 12.16.0

### ISSUE THREAD

**Issue by aslamy** [GeekInTheNorth/Stott.Optimizely.RobotsHandler#59]
Description:
After updating to Optimizely CMS version 12.16.0 and above, I observed that the [Stott.Optimizely.RobotsHandler] is no longer compatible.

Steps to reproduce:

Install Optimizely CMS version 12.16.0 or later.
Install or activate the [Stott.Optimizely.RobotsHandler].

**Comment by GeekInTheNorth** [comment]
@aslamy can you tell me which version of the module you are installing with CMS 12.16.0?

**Comment by GeekInTheNorth** [comment]
@aslamy Just to clarify, I have the current verified CMS and Robots Handler version combinations in DXP as of this morning:

| CMS Version (CMS Core Version) | Robots Handler |
|------|-------------------|
| 12.23.0 (12.19.0) | 2.6.2 |
| 12.22.7 (12.18.0) | 2.6.1 |
| 12.18.0 (12.13.1) | 2.6.1 |

**Comment by mikemalloy-commscope** [comment]
I've got Robots Handkler 2.6.2 with CMS 12.24.0 and it's working OK.

**Comment by GeekInTheNorth** [comment]
@aslamy can you confirm whether you are still having an issue or not? I will assume this is not an issue if a response is not received within a week and I will then close this issue.

**Comment by GeekInTheNorth** [comment]
Closing as this has been tested as working on multiple builds and no further communication has been received.
