### ISSUE TITLE
Add the ability to specify a domain for a Robots.txt entry

### ISSUE THREAD

**Issue by GeekInTheNorth** [GeekInTheNorth/Stott.Optimizely.RobotsHandler#68]
Currently the robots.txt is saved per site configuration and may want to be specific per host as well.

Requirements
- Allow Robots.txt entries to be saved by:
  - Site (Current).
  - Site & Host (Additional).
- Resolve Robots.txt entries in this order:
  - Matches Configuration for both Site & Host.
  - Matches Configuration for Site without Host configuration.
  - Return the default robots.txt which is disallow all

Note: Will need to rethink the list where no items have been defined.

**Comment by aegmiller824** [comment]
I really need this for a client. Any idea when it might be added?

**Comment by paulmcgann** [comment]
Hi @aegmiller824,

I would hope to have the changes made in the next few weeks. I am aiming towards the 19th April 2024.

Please note we work on this in our free time, so this is a best endeavour.

**Comment by aegmiller824** [comment]
Many thanks! A virtual coffee on me 😊

**Comment by aegmiller824** [comment]
Checking back in. Any update on this enhancement?

**Comment by GeekInTheNorth** [comment]
@aegmiller824 The changes are quite extensive as it requires some underlying assumption changes that affect all data journeys within the solution. Please note this hasn't been forgotten about.

**Comment by GeekInTheNorth** [comment]
Just to provide a progress update:

Completed:
- Data storage updated to include additional properties to support selecting a host
- Edit Modal updated to allow for the selection of "Default" or a specific Host entry
- List View updated to show "Default" or the specific Host the robots content is applied for
- List View updated to a show a psudeo default entry if a default does not exist for the site.  This shows the fallback behaviour.

Pending:
- Add a new "Create" modal that will allow you to start from an empty configuration and to choose a site and a set of hosts.
- Update the /robots.txt controller end point to handle host specific content

**Comment by GeekInTheNorth** [comment]
Changes have been completed, a new release package will be created soon.

**Comment by GeekInTheNorth** [comment]
I have found and fixed a couple of bugs that have been found in testing. 

A 3.0.0.2 Beta release is on nuget which I've now deployed into my test environment.

I'll comment here when a full release is made.

**Comment by GeekInTheNorth** [comment]
Noted a couple of tiny updates for the user interface:

- When creating a new robots config, if there is a conflict, then the alert banner refers to the site name as 'null'.
  - To be fixed for 3.0.0
- When opening the Add Configuration modal, the robots content should not be persisted
  - To be fixed for 3.0.0
- If the save is prevented due to a conflict, it should show as an inline error in the modal. pushing this out to a toast and closing the modal is not a good user experience
  - Might defer this as a 3.1.0 instead of a 3.0.0 release

**Comment by GeekInTheNorth** [comment]
@aegmiller824 Release 3.0.0 is now available on nuget.org and api.nuget.optimizely.com
