### ISSUE TITLE
Admin URL currently accessible when not logged in

### ISSUE THREAD

**Issue by jhope-kc** [GeekInTheNorth/Stott.Optimizely.RobotsHandler#79]
Hi

We have noticed that the `/stott.robotshandler/administration` is accessible to users who are not logged in.  
![robots-error](https://github.com/user-attachments/assets/e09cc2c9-9992-4a2f-bade-e4a4be197dee)
They are unable to to access any of the information at least. It looks like the Authorize attribute is missing on the Controller

Thanks

**Comment by GeekInTheNorth** [comment]
Hello @jhope-kc 

Thank you for the feedback, The API Controller has the Authorize attribute, so at the very least the ability to View / Edit / Delete the robots configuration is protected.  I'll get the missing attribute added and build this out as a hotfix for you.

Regards,
Mark Stott

**Comment by GeekInTheNorth** [comment]
@jhope-kc I have created this as a 3.0.1 build and submitted it to both nuget.org and nuget.optimizely.com
